<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Registers the built-in form modules as services so the admin can price them.
     * Safe to re-run: it never overwrites a coin cost the admin has already set.
     */
    public function run(): void
    {
        $services = [
            [
                'name' => 'Marriage Certificate',
                'slug' => 'marriage-certificate',
                'description' => 'Fill the marriage certificate form and print it instantly.',
                'icon' => '💍',
                'coin_cost' => 10,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'marriage_form',
                'sort_order' => 1,
            ],
            [
                'name' => 'Birth Certificate Name Add',
                'slug' => 'birth-certificate',
                'description' => 'Enter Certificate / Registration Number to download PDF instantly (Color & B&W Options).',
                'icon' => '👶',
                'coin_cost' => 0,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'birth_record',
                'sort_order' => 2,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
            ],
            [
                'name' => 'Birth Certificate Download',
                'slug' => 'crs-birth-portal',
                'description' => 'जन्म प्रमाण पत्र / रजिस्ट्रेशन नंबर दर्ज करके तुरंत PDF डाउनलोड करें।',
                'icon' => '👶',
                'coin_cost' => 0,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'crs_portal',
                'sort_order' => 2,
                'is_active' => false,
                'visibility' => Service::VISIBILITY_PRIVATE,
            ],
            [
                'name' => 'Haryana Domicile',
                'slug' => 'haryana-domicile',
                'description' => 'Generate a Haryana domicile certificate.',
                'icon' => '📜',
                'coin_cost' => 10,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'haryana_domicile',
                'sort_order' => 3,
            ],
            [
                'name' => 'DHBVN Electricity Bill',
                'slug' => 'dhbvn-electricity-bill',
                'description' => 'Dakshin Haryana Bijli Vitran Nigam (DHBVN) duplicate electricity bill instant PDF download.',
                'icon' => '⚡',
                'coin_cost' => 0,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'dhbvn_electricity_bill',
                'sort_order' => 5,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
            ],
            [
                'name' => 'UHBVN Electricity Bill',
                'slug' => 'uhbvn-electricity-bill',
                'description' => 'Uttar Haryana Bijli Vitran Nigam (UHBVN) duplicate electricity bill instant PDF download.',
                'icon' => '⚡',
                'coin_cost' => 0,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'uhbvn_electricity_bill',
                'sort_order' => 6,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
            ],
            [
                'name' => 'Vehicle Details (RC)',
                'slug' => 'vehicle-details',
                'description' => 'Instantly download complete RC details PDF by entering the vehicle registration number.',
                'icon' => '🚗',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'vehicle_details',
                'sort_order' => 6,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Vehicle to Mobile Number',
                'slug' => 'vehicle-to-mobile',
                'description' => 'Find linked mobile number and chassis details from vehicle registration number.',
                'icon' => '🚗',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'vehicle_to_mobile',
                'sort_order' => 7,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Passport Photo Maker',
                'slug' => 'passport-maker',
                'description' => 'Create passport size photos with AI background removal and print-ready layouts.',
                'icon' => 'fas fa-id-badge',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'passport_maker',
                'sort_order' => 8,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Passport Apply',
                'slug' => 'passport-apply',
                'description' => 'Online Passport application assistance. Complete form filling, document verification, and appointment booking.',
                'icon' => '🛂',
                'coin_cost' => 2750,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'passport_apply',
                'sort_order' => 29,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar To Pan Unmasked Instant',
                'slug' => 'aadhar-to-pan',
                'description' => 'Instantly find the unmasked PAN number linked to an Aadhaar number.',
                'icon' => '🔍',
                'coin_cost' => 69,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_to_pan',
                'sort_order' => 9,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Saral Certificate Status',
                'slug' => 'saral-status',
                'description' => 'Check the status of any Saral Certificate using its reference number instantly.',
                'icon' => '📃',
                'coin_cost' => 0,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'saral_status',
                'sort_order' => 10,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar To Name',
                'slug' => 'aadhar-to-name',
                'description' => 'Find name details using Aadhar number.',
                'icon' => 'badge',
                'coin_cost' => 19,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_to_name',
                'sort_order' => 11,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar To Pan Mask',
                'slug' => 'aadhar-to-mask-pan',
                'description' => 'Find masked PAN card number linked to an Aadhar number.',
                'icon' => 'credit_card',
                'coin_cost' => 19,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_to_mask_pan',
                'sort_order' => 12,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Smart PVC Card Maker',
                'slug' => 'pvc-card-maker',
                'description' => 'Generate Print-Ready PVC Front, Back & A4 Sheet from Haryana Family ID, Ayushman, Voter, PAN, e-Shram PDFs.',
                'icon' => '🪪',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'pvc_card_maker',
                'sort_order' => 14,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Haryana Family ID PVC Card',
                'slug' => 'haryana-familyid-pvc',
                'description' => 'Generate Print-Ready PVC Front, Back & A4 Sheet from Haryana Family ID PDF.',
                'icon' => '🆔',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'haryana_familyid_pvc',
                'sort_order' => 15,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhaar PVC Card Maker',
                'slug' => 'aadhaar-pvc-card',
                'description' => 'Generate Print-Ready PVC Front & Back Card from e-Aadhaar PDF.',
                'icon' => '🔍',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhaar_pvc',
                'sort_order' => 16,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Ayushman 3Lakh Income Make',
                'slug' => 'ayushman-3lakh-income-make',
                'description' => 'Chirayu Haryana - Apply & Make Ayushman Bharat Golden Card for 1.80L to 3.00L annual income families.',
                'icon' => '🏥',
                'coin_cost' => 0,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'ayushman_3lakh_income_make',
                'sort_order' => 16,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Ayushman Bharat PVC Card',
                'slug' => 'ayushman-pvc',
                'description' => 'Generate Print-Ready PVC Front & Back Card from Ayushman Golden Card PDF.',
                'icon' => '🏥',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'ayushman_pvc',
                'sort_order' => 17,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Voter (E-EPIC) PVC Card',
                'slug' => 'voter-pvc-card',
                'description' => 'Generate Print-Ready PVC Front & Back Card from Voter e-EPIC PDF.',
                'icon' => '🗳️',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'voter_pvc',
                'sort_order' => 18,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'PAN Card (NSDL) PVC',
                'slug' => 'pan-nsdl-pvc',
                'description' => 'Generate Print-Ready PVC Front & Back Card from NSDL e-PAN PDF.',
                'icon' => '💳',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'pan_nsdl_pvc',
                'sort_order' => 19,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'e-Shram PVC Card Maker',
                'slug' => 'eshram-pvc-card',
                'description' => 'Generate Print-Ready PVC Front & Back Card from e-Shram PDF.',
                'icon' => '👷',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'eshram_pvc',
                'sort_order' => 22,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Make Driving Licence (Cards)',
                'slug' => 'make-driving-licence-card',
                'description' => 'Generate Print-Ready PVC Front, Back & A4 Sheet from Driving Licence Number and Date of Birth.',
                'icon' => '🚗',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'make_driving_licence_card',
                'sort_order' => 23,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'PM Vishwakarma PVC Card',
                'slug' => 'pmvishwakarma-pvc',
                'description' => 'Generate Print-Ready PVC Front & Back Card from PM Vishwakarma PDF.',
                'icon' => '🛠️',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'pmvishwakarma_pvc',
                'sort_order' => 25,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'APAAR / Student ID PVC Card',
                'slug' => 'aapar-pvc',
                'description' => 'Generate Print-Ready PVC Front & Back Card from APAAR Student ID PDF.',
                'icon' => '🎓',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aapar_pvc',
                'sort_order' => 26,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'QR to Print (Smart Counter)',
                'slug' => 'qr-to-print',
                'description' => 'Direct QR Scan & Auto Print from Customer Mobile to Shop Printer.',
                'icon' => '🖨️',
                'coin_cost' => 0,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'qr_to_print',
                'sort_order' => 27,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Verify IFSC Code',
                'slug' => 'verify-ifsc-code',
                'description' => 'Verify IFSC code to get complete bank & branch details.',
                'icon' => '🏦',
                'coin_cost' => 9,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'verify_ifsc_code',
                'sort_order' => 28,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Kundli Generator (Janam Kundli)',
                'slug' => 'kundli-generator',
                'description' => 'Generate and print detailed Janam Kundli with charts & planetary predictions.',
                'icon' => '🪐',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'kundli_generator',
                'sort_order' => 30,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PRIVATE,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar Card to PPP ID Instant',
                'slug' => 'aadhar-to-ppp-id',
                'description' => 'Instantly retrieve Haryana Family ID (PPP ID) using 12-digit Aadhaar Number without OTP.',
                'icon' => '🆔',
                'coin_cost' => 0,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_to_ppp_id',
                'sort_order' => 31,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'PPP ID to Aadhar Number (All Members)',
                'slug' => 'ppp-to-aadhar-all-members',
                'description' => 'Fetch unmasked Aadhaar Card numbers of all family members from PPP ID without OTP.',
                'icon' => '👥',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'ppp_to_aadhar_all_members',
                'sort_order' => 32,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'PPP ID to Mobile Number (All Members)',
                'slug' => 'ppp-to-mobile-all-members',
                'description' => 'Fetch linked mobile numbers of all family members from PPP ID without OTP.',
                'icon' => '📱',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'ppp_to_mobile_all_members',
                'sort_order' => 33,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'PPP ID to Bank Account & IFSC Code',
                'slug' => 'ppp-to-bank-details',
                'description' => 'Fetch bank account numbers, IFSC codes, and branch details from PPP ID without OTP.',
                'icon' => '🏦',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'ppp_to_bank_details',
                'sort_order' => 34,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Vehicle PUC (Without OTP)',
                'slug' => 'vehicle-puc-without-otp',
                'description' => 'Download Vehicle Pollution Under Control (PUC) certificate details instantly without OTP.',
                'icon' => '🚗',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'vehicle_puc_without_otp',
                'sort_order' => 35,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Vehicle PUC (With OTP)',
                'slug' => 'vehicle-puc-with-otp',
                'description' => 'Verify with OTP and download official Vehicle PUC Certificate PDF.',
                'icon' => '🔐',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'vehicle_puc_with_otp',
                'sort_order' => 36,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'S.I.R Voter Card List',
                'slug' => 'sir-voter-card-list',
                'description' => 'Search electoral roll and voter card list by State, District, Assembly, or EPIC number.',
                'icon' => '🗳️',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'sir_voter_card_list',
                'sort_order' => 37,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Voter Card Manual Maker',
                'slug' => 'voter-card-manual-maker',
                'description' => 'Create and customize manual Voter Card (EPIC) with photo, signature, and QR code.',
                'icon' => '🗳️',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'voter_card_manual_maker',
                'sort_order' => 39,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar Card Manual',
                'slug' => 'aadhar-card-manual',
                'description' => 'Generate and customize manual Aadhaar Card with photo, QR code, and regional language details.',
                'icon' => '🆔',
                'coin_cost' => 25,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_card_manual',
                'sort_order' => 40,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar Card Mobile Number Update',
                'slug' => 'aadhar-mobile-update',
                'description' => 'Link or update mobile number on Aadhaar Card with instant acknowledgement receipt.',
                'icon' => '📱',
                'coin_cost' => 25,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_mobile_update',
                'sort_order' => 42,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar Card DOB Change',
                'slug' => 'aadhar-dob-change',
                'description' => 'Apply for Date of Birth (DOB) correction on Aadhaar Card with supporting documents.',
                'icon' => '📅',
                'coin_cost' => 25,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_dob_change',
                'sort_order' => 43,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar Card Surname Change',
                'slug' => 'aadhar-surname-change',
                'description' => 'Update or change surname/last name on Aadhaar Card after marriage or legal correction.',
                'icon' => '👤',
                'coin_cost' => 25,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_surname_change',
                'sort_order' => 44,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'Aadhar Card Full Name Change',
                'slug' => 'aadhar-full-name-change',
                'description' => 'Correct or update full legal name on Aadhaar Card with identity proof verification.',
                'icon' => '🪪',
                'coin_cost' => 25,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'aadhar_full_name_change',
                'sort_order' => 45,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
            [
                'name' => 'ABHA Health ID Make',
                'slug' => 'abha-health-id-make',
                'description' => 'Create and download new Ayushman Bharat Health Account (ABHA) Card online via ABDM v3.',
                'icon' => '🏥',
                'coin_cost' => 20,
                'kind' => Service::KIND_MODULE,
                'module_key' => 'abha_health_id_make',
                'sort_order' => 46,
                'is_active' => true,
                'visibility' => Service::VISIBILITY_PUBLIC,
                'is_premium' => false,
                'unlock_cost' => 0,
            ],
        ];

        foreach ($services as $service) {
            $existing = Service::withTrashed()->where('slug', $service['slug'])->first();
            if (!$existing && $service['slug'] === 'make-driving-licence-card') {
                $existing = Service::withTrashed()->where('slug', 'driving-licence-pvc')->first();
            }

            // If the service was removed/deleted by admin, do NOT recreate or restore it!
            if ($existing && $existing->trashed()) {
                continue;
            }

            if (!$existing) {
                $service['is_active'] = $service['is_active'] ?? true;
                $service['visibility'] = $service['visibility'] ?? Service::VISIBILITY_PUBLIC;
                $service['is_premium'] = $service['is_premium'] ?? false;
                $service['unlock_cost'] = $service['unlock_cost'] ?? 0;
                $created = Service::create($service);
                $targetService = $created;
            } else {
                // Update only code-driven metadata.
                // NEVER overwrite admin-controlled attributes: is_active, coin_cost, visibility, is_premium, unlock_cost!
                $existing->update([
                    'name' => $service['name'],
                    'slug' => $service['slug'],
                    'kind' => $service['kind'],
                    'module_key' => $service['module_key'],
                    'icon' => $service['icon'],
                    'description' => $service['description'],
                    'sort_order' => $service['sort_order'],
                ]);
                $targetService = $existing;
            }
        }

        // Clean up old and duplicate services that are no longer used
        $oldSlugs = [
            'telegram-num',
            'telegram-aadhar',
            'telegram-familyinfo',
            'telegram-pan',
            'telegram-ration',
            'mobile-to-details', // the old one
            'aadhar-update',
            'tenth-passbook',
            'haryana-domocile',
            'rc-pdf-instant',
            'dl-pdf-instant',
            'pan-details-instant',
            'healthid-pvc',
            'aadhar-card-address-change',
            'voter-card-manual-address-change',
            'pdf-editor',
            'pan-full-details-instant',
            'pan-uti-pvc',
            'pan-instant-pvc',
            'pan-card',
        ];

        $removeNames = [
            'Voter Card Manual For Address Change',
            'PDF Editor',
            'Pan Details Server Instant',
            'PAN Full Details Instant',
            'PAN Card (UTIITSL) PVC',
            'PAN Card (Instant e-Filing) PVC',
            'PAN Card',
        ];

        Service::withTrashed()
            ->whereIn('slug', $oldSlugs)
            ->orWhereIn('name', $removeNames)
            ->orWhere('module_key', 'tenth_passbook')
            ->forceDelete();
    }
}
