/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
        './resources/js/**/*.js',
    ],
    darkMode: "class",
    theme: {
        extend: {
            keyframes: {
                'marquee-ltr': {
                    '0%': { transform: 'translateX(-100%)' },
                    '100%': { transform: 'translateX(100%)' },
                },
            },
            animation: {
                'marquee-ltr': 'marquee-ltr 15s linear infinite',
            },
            "colors": {
                "primary-fixed-dim": "#adc6ff",
                "surface-container": "#eeedf3",
                "error": "#ba1a1a",
                "on-primary-fixed": "#001a41",
                "inverse-surface": "#2f3034",
                "surface-variant": "#e3e2e7",
                "surface-tint": "#005bc1",
                "surface-container-low": "#f4f3f8",
                "background": "#faf9fe",
                "tertiary-fixed-dim": "#53e16f",
                "tertiary": "#006b27",
                "secondary-fixed": "#e2dfff",
                "on-secondary-container": "#fffbff",
                "error-container": "#ffdad6",
                "tertiary-fixed": "#72fe88",
                "on-secondary": "#ffffff",
                "primary": "#0058bc",
                "secondary": "#4c4aca",
                "on-primary-container": "#fefcff",
                "on-tertiary-container": "#f7fff2",
                "inverse-primary": "#adc6ff",
                "outline": "#717786",
                "primary-fixed": "#d8e2ff",
                "surface-container-lowest": "#ffffff",
                "surface-container-high": "#e9e7ed",
                "on-secondary-fixed-variant": "#3631b4",
                "on-tertiary-fixed-variant": "#00531c",
                "tertiary-container": "#008733",
                "secondary-fixed-dim": "#c2c1ff",
                "on-primary": "#ffffff",
                "outline-variant": "#c1c6d7",
                "on-error": "#ffffff",
                "on-primary-fixed-variant": "#004493",
                "inverse-on-surface": "#f1f0f5",
                "on-secondary-fixed": "#0c006a",
                "on-background": "#1a1b1f",
                "on-surface": "#1a1b1f",
                "secondary-container": "#6664e4",
                "on-surface-variant": "#414755",
                "on-tertiary-fixed": "#002107",
                "on-error-container": "#93000a",
                "surface": "#faf9fe",
                "surface-dim": "#dad9df",
                "on-tertiary": "#ffffff",
                "surface-bright": "#faf9fe",
                "primary-container": "#0070eb",
                "surface-container-highest": "#e3e2e7"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "gutter": "24px",
                "stack-md": "16px",
                "base": "8px",
                "margin-mobile": "16px",
                "stack-lg": "32px",
                "margin-desktop": "64px",
                "stack-sm": "8px"
            },
            "fontFamily": {
                "body-sm": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "label-md": ["Inter"],
                "display-lg": ["Inter"],
                "headline-md": ["Inter"],
                "body-md": ["Inter"],
                "body-lg": ["Inter"],
                "label-sm": ["Inter"],
                "headline-lg": ["Inter"]
            },
            "fontSize": {
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
            }
        },
    },
    plugins: [],
};
